### Listar todas las asistencias
GET http://localhost:3000/api/assistances
Content-Type: application/json

###

### Filtrar asistencias por estudiante y estado
GET http://localhost:3000/api/assistances?studentId=1&status=ACTIVO
Content-Type: application/json

###

### Obtener asistencia por ID
GET http://localhost:3000/api/assistances/1
Content-Type: application/json

###

### Crear una nueva asistencia
POST http://localhost:3000/api/assistances/create
Content-Type: application/json

{
  "studentId": 1,
  "routeId": 1,
  "busId": 1,
  "date": "2024-01-15",
  "time": "07:45:00",
  "status": "ACTIVO"
}
