@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwMzI2MjU3LCJleHAiOjE3NjAzMjc0NTd9.8OrjxPfaU7DtADk9o4s5neJ52oVC57Mo-uy419VqM2w

### Obtener todas las asistencias
GET {{baseUrl}}/api/assistances
Authorization: Bearer {{token}}

###

### Crear una asistencia
POST {{baseUrl}}/api/assistances
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studentId": 4,
  "routeId": 2,
  "busId": 2,
  "date": "2024-09-15",
  "time": "07:30:00",
  "status": "ACTIVO"
}

###

### Obtener asistencia por ID
GET {{baseUrl}}/api/assistances/2
Authorization: Bearer {{token}}

###

### Actualizar una asistencia
PUT {{baseUrl}}/api/assistances/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studentId": 4,
  "routeId": 4,
  "busId": 2,
  "date": "2022-09-16",
  "time": "07:45:00",
  "status": "ACTIVO"
}

###

### Eliminar una asistencia físicamente
DELETE {{baseUrl}}/api/assistances/1
Authorization: Bearer {{token}}

###

### Eliminar una asistencia lógicamente
PATCH {{baseUrl}}/api/assistances/2/deactivate
Authorization: Bearer {{token}}
