@baseUrl = http://localhost:4000

### ================== AUTENTICACIÓN ==================

### Registrar usuario
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "operario",
  "email": "operario@uniguajira.com",
  "password": "6640",
  "status": "ACTIVO",
  "avatar": "https://example.com/avatar.png"
}

###

### Iniciar sesión
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "admin@uniguajira.com",
  "password": "6640"
}

###

### Refrescar tokens
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYwMzA1ODUxLCJleHAiOjE3NjA5MTA2NTF9.xyckAdXqlcgFDq7lveEjulVCtSPnJ1s7WtHi9OwMfTc"
}
