@baseUrl = http://localhost:4000

### ================== AUTENTICACIÓN ==================

### Registrar usuario
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "supervisor",
  "email": "supervisor@uniguajira.com",
  "password": "6640",
  "status": "ACTIVO",
  "avatar": "https://example.com/avatar.png"
}

###

### Iniciar sesión
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "carlos.gomez@example.com",
  "password": "123456789"
}

###

### Refrescar tokens
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": ""
}
