@baseUrl = http://localhost:4000

### ================== AUTENTICACIÓN ==================

### Registrar usuario
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "operario",
  "email": "operario@uniguajira.com",
  "password": "6640",
  "status": "ACTIVO",
  "avatar": "https://example.com/avatar.png"
}

###

### Iniciar sesión
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "supervisor@uniguajira.com",
  "password": "6640"
}
