
@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYwMzA1ODUxLCJleHAiOjE3NjAzMDcwNTF9.ivZ30x3rp0fOHCGnm3xgBfeW6vDpwiPd6h7NXI_D_TA

### ================== TOKENS DE REFRESCO ==================

### Obtener todos los tokens de refresco
GET {{baseUrl}}/api/auth/refresh-tokens
Authorization: Bearer {{token}}

###

### Crear un token de refresco (para pruebas)
POST {{baseUrl}}/api/auth/refresh-tokens
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user_id": 1,
  "token": "demo-refresh-token",
  "device_info": "http-client",
  "status": "ACTIVO",
  "expires_at": "2024-09-30T12:00:00Z"
}

###

### Obtener token de refresco por ID
GET {{baseUrl}}/api/auth/refresh-tokens/1
Authorization: Bearer {{token}}

###

### Actualizar un token de refresco
PUT {{baseUrl}}/api/auth/refresh-tokens/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user_id": 1,
  "token": "demo-refresh-token-actualizado",
  "device_info": "http-client",
  "status": "ACTIVO",
  "expires_at": "2024-10-15T12:00:00Z"
}

###

### Eliminar un token de refresco físicamente
DELETE {{baseUrl}}/api/auth/refresh-tokens/1
Authorization: Bearer {{token}}

###

### Eliminar un token de refresco lógicamente
PATCH {{baseUrl}}/api/auth/refresh-tokens/1/deactivate
Authorization: Bearer {{token}}
