@baseUrl = http://localhost:4000
@token =

### ================== RECURSOS ==================

### Obtener todos los recursos
GET {{baseUrl}}/api/auth/resources
Authorization: Bearer {{token}}

###

### Crear un recurso
POST {{baseUrl}}/api/auth/resources
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path": "/api/example",
  "method": "GET",
  "status": "ACTIVO"
}

###

### Obtener recurso por ID
GET {{baseUrl}}/api/auth/resources/1
Authorization: Bearer {{token}}

###

### Actualizar un recurso
PUT {{baseUrl}}/api/auth/resources/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "path": "/api/example",
  "method": "POST",
  "status": "ACTIVO"
}

###

### Eliminar un recurso físicamente
DELETE {{baseUrl}}/api/auth/resources/1
Authorization: Bearer {{token}}

###

### Eliminar un recurso lógicamente
PATCH {{baseUrl}}/api/auth/resources/1/deactivate
Authorization: Bearer {{token}}
