@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwMzA2MzI5LCJleHAiOjE3NjAzMDc1Mjl9.0rEszTwlUiKtYygWC48CLtKydJYqRJKq7xfeJjcHbNA

### ================== BUSES ==================

### Obtener todos los buses
GET {{baseUrl}}/api/buses
Authorization: Bearer {{token}}

###

### Crear un bus
POST {{baseUrl}}/api/buses
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plate": "ABC-123",
  "capacity": 45,
  "mileage": 120000,
  "model": "Sprinter",
  "brand": "Mercedes",
  "year": 2018,
  "color": "Blanco",
  "status": "ACTIVO",
  "insuranceExpiry": "2025-01-01",
  "lastMaintenance": "2024-05-01",
  "nextMaintenance": "2024-11-01"
}

###

### Obtener bus por ID
GET {{baseUrl}}/api/buses/1
Authorization: Bearer {{token}}

###

### Actualizar un bus
PUT {{baseUrl}}/api/buses/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plate": "ABC-124",
  "capacity": 48,
  "mileage": 121000,
  "model": "Sprinter",
  "brand": "Mercedes",
  "year": 2019,
  "color": "Azul",
  "status": "ACTIVO",
  "insuranceExpiry": "2025-01-01",
  "lastMaintenance": "2024-06-01",
  "nextMaintenance": "2024-12-01"
}

###

### Eliminar un bus físicamente
DELETE {{baseUrl}}/api/buses/1
Authorization: Bearer {{token}}

###

### Eliminar un bus lógicamente
PATCH {{baseUrl}}/api/buses/7/deactivate
Authorization: Bearer {{token}}
