@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwMzI4MzU5LCJleHAiOjE3NjAzMjk1NTl9.R_UAeptTDKDIpYt-5LmYY-3A1IQWQVvCob7pt_YWxAM

### ================== TUTORES ==================

### Obtener todos los tutores
GET {{baseUrl}}/api/guardians
Authorization: Bearer {{token}}

###

### Crear un tutor
POST {{baseUrl}}/api/guardians
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Lopez",
  "document": "87655321",
  "phone": "555-8888",
  "email": "mariaa.loper@example.com",
  "relationship": "Madre",
  "address": "Calle Secundaria 456",
  "status": "ACTIVO"
}

###

### Obtener tutor por ID
GET {{baseUrl}}/api/guardians/1
Authorization: Bearer {{token}}

###

### Actualizar un tutor
PUT {{baseUrl}}/api/guardians/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Maria",
  "lastName": "Lopez",
  "document": "87654321",
  "phone": "555-9999",
  "email": "maria.lopez@example.com",
  "relationship": "Madre",
  "address": "Calle Actualizada 789",
  "status": "ACTIVO"
}

###

### Eliminar un tutor físicamente
DELETE {{baseUrl}}/api/guardians/1
Authorization: Bearer {{token}}

###

### Eliminar un tutor lógicamente
PATCH {{baseUrl}}/api/guardians/1/deactivate
Authorization: Bearer {{token}}

### Cambio de contraseña 
POST {{baseUrl}}/api/auth/users/reset-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword": "123456789",
  "newPassword": "nuevaClaveSegura123"
}
