@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwMzA2MzI5LCJleHAiOjE3NjAzMDc1Mjl9.0rEszTwlUiKtYygWC48CLtKydJYqRJKq7xfeJjcHbNA

### ================== ASIGNACIONES DE RUTA ==================

### Obtener todas las asignaciones
GET {{baseUrl}}/api/route-assignments
Authorization: Bearer {{token}}

###

### Crear una asignación de ruta
POST {{baseUrl}}/api/route-assignments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "routeId": 1,
  "busId": 1,
  "driverId": 1,
  "startDate": "2024-09-01",
  "endDate": null,
  "status": "ACTIVO"
}

###

### Obtener asignación por ID
GET {{baseUrl}}/api/route-assignments/1
Authorization: Bearer {{token}}

###

### Actualizar una asignación de ruta
PUT {{baseUrl}}/api/route-assignments/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "routeId": 1,
  "busId": 1,
  "driverId": 2,
  "startDate": "2024-09-01",
  "endDate": "2024-12-31",
  "status": "ACTIVO"
}

###

### Eliminar una asignación físicamente
DELETE {{baseUrl}}/api/route-assignments/1
Authorization: Bearer {{token}}

###

### Eliminar una asignación lógicamente
PATCH {{baseUrl}}/api/route-assignments/1/deactivate
Authorization: Bearer {{token}}
