### Listar todas las rutas
GET http://localhost:3000/api/routes
Content-Type: application/json

###

### Filtrar rutas por estado
GET http://localhost:3000/api/routes?status=ACTIVO
Content-Type: application/json

###

### Obtener ruta por ID
GET http://localhost:3000/api/routes/1
Content-Type: application/json
