@baseUrl = http://localhost:4000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzYwMzA1ODUxLCJleHAiOjE3NjAzMDcwNTF9.ivZ30x3rp0fOHCGnm3xgBfeW6vDpwiPd6h7NXI_D_TA

### ================== USUARIOS ==================

### Listar usuarios
GET {{baseUrl}}/api/auth/users
Authorization: Bearer {{token}}

###

### Cambiar contraseña propia
POST {{baseUrl}}/api/auth/users/reset-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentPassword": "123456789",
  "newPassword": "nuevaClaveSegura123"
}
